apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickcounter
  namespace: clickapp
  labels:
    app: clickcounter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickcounter
  template:
    metadata:
      labels:
        app: clickcounter
    spec:
      containers:
      - name: clickcounter
        image: kodekloud/click-counter
        ports:
          - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis