apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: clickapp
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379